### ISSUE TITLE
The link to the Chart JS docs is incorrect

### ISSUE THREAD

**Issue by SteveHawes** [Servoy/svyChartJS#12]
On the wiki for the plugin it gives a link to the documentation for Chart JS:
![image](https://user-images.githubusercontent.com/23415735/126524697-38b4f2c0-1cf9-4302-8b6d-ec26229fd26d.png)
This link takes you to the documentation for V3.4.1 but the plugin is using V2.9.4. 

Please update either the link to the documentation or better still update the plugin to use V3.x.x of the Chart JS library as I have just spent a few hours trying to figure out why my chart didn't work and the problem was down to me using the V3.x.x version of the options for axes scales instead of the v2.9.4 version.

**Comment by tuanway** [comment]
Sure, i'll update it now.

We don't have any plans to upgrade to that version at the moment, as there are many different complications with existing plugins.
