### ISSUE TITLE
Callback function not working

### ISSUE THREAD

**Issue by SteveHawes** [Servoy/svyChartJS#13]
I have tried to use a callback for setting the labels on the y axis using the suggested method for creating a callback function but I am getting an error as follows:

`ERROR org.sablo.BrowserConsole - Uncaught TypeError: #<Object> is not a function
http://localhost:8183/svychartjs/lib/js/Chart.js:11685:23
TypeError: #<Object> is not a function`

My callback function is defined as follows:

	var scale_callback = {
		isFunction: true,
		params: ['value', 'index', 'array'],
		expression: "return (value < 1000000) ? value/1000 + 'K' : value/1000000 + 'M';"
	}

And my chart options are:

	var options = {
		responsive: true,
		maintainAspectRatio: false,
		scales: {
			yAxes: [
				{
					id: 'y1',
					type: 'linear',
					position: 'left',
					scaleLabel: {
						display: true,
						labelString: '12 Month Revenue',
						fontColor: distinctColors[0],
						fontSize: 14
					},
					ticks: {
						callback: scale_callback
					}
				}
			]
		},
		legend: {
			position: 'top'
		}
	}

If I remove the

					ticks: {
						callback: scale_callback
					}

section then everything works OK.

My code was constructed using the suggestion for callbacks in the Wiki and referencing the "Creating Custom Tick Formats" of the official documentation at https://www.chartjs.org/docs/2.9.4/axes/labelling.html

**Comment by tuanway** [comment]
Please refer to the following ticket as updates come through.
https://support.servoy.com/browse/SVYX-280

**Comment by seanthomasdevlin** [comment]
The expression can become invalid if the value parameter is undefined, which could be the case.  Perhaps try doing something like below:


`expression: "if(value) {return (value < 1000000) ? value/1000 + 'K' : value/1000000 + 'M';}"`

**Comment by SteveHawes** [comment]
Hi Sean,

That was the problem and your solution fixed it. Maybe update the Wiki with this?

Thanks
