### ISSUE TITLE
Expose the generateLegend() API

### ISSUE THREAD

**Issue by biannetta** [Servoy/svyChartJS#6]
ChartJS has a generateLegend(); function which returns an HTML rendered version of the legends instead of placing it in the Canvas object. This would allow for styling and formatting of the chart legends.

See this fiddle example [http://jsfiddle.net/vrwjfg9z/](http://jsfiddle.net/vrwjfg9z/)

**Comment by tuanway** [comment]
It's easy to return the generateLegend html string and I've already done it in practice.  However using it in combination with any other component in Servoy will be a bit limiting (especially for styling purposes)
As none of our default [label or html](https://support.servoy.com/browse/SVY-11442) elements will render the style tags correctly (missing the associated background colors).

* You would have to use this **API** in combination with **label/html** component that overrides the default angular sanitization, One that's using [$sce](https://docs.angularjs.org/api/ng/service/$sce) perhaps.

**Comment by tuanway** [comment]
Closing this item - this will be available in next release, as well as an example.
